apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yllz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-yllz@sha256:bef0a05031942fde5e13288ff82bb81668f0f0e27fe41305fbfb37cac3bb8c5d
        name: my-nodejs
        resources: {}
status: {}
